// <auto-generated />
using System;
using Dashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dashboard.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Dashboard.Infrastructure.Entity.BugEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bugs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(3980),
                            Message = "Error number: 1",
                            System = "System number: 3848321d-0c8b-4ed9-8c2c-2db49ee43569"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(3987),
                            Message = "Error number: 2",
                            System = "System number: b6c03ce0-6b57-4ac8-8a33-3d5b77beea42"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(3991),
                            Message = "Error number: 3",
                            System = "System number: c4fe8f45-a598-4124-a1ff-e6aa2a7d068e"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(3995),
                            Message = "Error number: 4",
                            System = "System number: f661292b-a5a6-4b8a-80d8-d685ec19e0b8"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4000),
                            Message = "Error number: 5",
                            System = "System number: eafa2179-ba04-4733-a7d7-acd69adba60c"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4006),
                            Message = "Error number: 6",
                            System = "System number: 9491f1f1-aac4-4842-ba49-bd0f5986359c"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4010),
                            Message = "Error number: 7",
                            System = "System number: 89f4a597-0c3c-438c-9394-313e6d3b1e55"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4014),
                            Message = "Error number: 8",
                            System = "System number: 5729329d-0d0c-4319-b246-4537f222ec13"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4020),
                            Message = "Error number: 9",
                            System = "System number: 41e29a09-eab3-476c-bf7f-d3640de1fcae"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4026),
                            Message = "Error number: 10",
                            System = "System number: 80eb793b-d571-4d65-bcec-8610db2bb3f7"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4030),
                            Message = "Error number: 11",
                            System = "System number: 67cf31af-e0e6-4fb5-b5a7-e6770a90ea8a"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4034),
                            Message = "Error number: 12",
                            System = "System number: a5b8c67c-f20c-4bc4-9a35-88b6b8876b10"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4038),
                            Message = "Error number: 13",
                            System = "System number: 9ceea228-227c-43b4-89cb-06ebcfbee49f"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4042),
                            Message = "Error number: 14",
                            System = "System number: 81662a95-dd59-4df1-b152-97ca0c495236"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4046),
                            Message = "Error number: 15",
                            System = "System number: 2a48828f-acfe-47b3-89a3-29adf86e44bf"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4050),
                            Message = "Error number: 16",
                            System = "System number: d016341f-0df2-4d0a-a526-8b2476b5ac76"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4055),
                            Message = "Error number: 17",
                            System = "System number: fbf2d44b-8b38-424f-8069-b07e2e57b127"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4060),
                            Message = "Error number: 18",
                            System = "System number: 764f4f66-5f1d-4381-9611-91d75cb00102"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4086),
                            Message = "Error number: 19",
                            System = "System number: 012edb58-3a47-48b8-b0f4-323b441cbcab"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4090),
                            Message = "Error number: 20",
                            System = "System number: a138193a-1bc5-4af1-9458-8d82839cae61"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4094),
                            Message = "Error number: 21",
                            System = "System number: 7f47c5b5-d751-4922-9c7f-faa0eeaa29ed"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4098),
                            Message = "Error number: 22",
                            System = "System number: 7639d711-51c0-4298-ad85-c3430481fdc1"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4102),
                            Message = "Error number: 23",
                            System = "System number: 0c822955-81f6-4265-8e46-43ba399cae48"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4106),
                            Message = "Error number: 24",
                            System = "System number: dd3e22a6-fa2d-4b4a-a036-a125d6089a46"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4112),
                            Message = "Error number: 25",
                            System = "System number: 99fc682d-6f6c-4764-9ff1-9cff85c7f0ae"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4116),
                            Message = "Error number: 26",
                            System = "System number: b5545e90-8532-452b-b781-ffdd606d38cc"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4119),
                            Message = "Error number: 27",
                            System = "System number: 4a12349f-342e-4180-8bc3-d1c197e7a4cd"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4123),
                            Message = "Error number: 28",
                            System = "System number: 8a3f9212-d04b-4bbd-a6c0-c10531f5e94b"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4127),
                            Message = "Error number: 29",
                            System = "System number: 03866970-92eb-409b-bb38-6ab633a38cfc"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4131),
                            Message = "Error number: 30",
                            System = "System number: 2bcd58d5-8f54-4279-aea7-cb3600e79973"
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4135),
                            Message = "Error number: 31",
                            System = "System number: d6b6641b-e962-49e6-aee4-4153f19f122f"
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4139),
                            Message = "Error number: 32",
                            System = "System number: 6eb9744c-edf5-4dfb-9acd-1fd1c8e6608b"
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4144),
                            Message = "Error number: 33",
                            System = "System number: bebb1d75-c108-4af7-abbc-600db9439152"
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4148),
                            Message = "Error number: 34",
                            System = "System number: 1fb576d7-443c-44b6-9040-0233ce2d2362"
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4152),
                            Message = "Error number: 35",
                            System = "System number: 8792e939-4b67-4942-a649-96270835f37a"
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4156),
                            Message = "Error number: 36",
                            System = "System number: e4fd0c36-17ae-4a56-98aa-bb786bffe4d9"
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4160),
                            Message = "Error number: 37",
                            System = "System number: 1928153b-dde2-4148-8b0b-aed73c8a78ed"
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4164),
                            Message = "Error number: 38",
                            System = "System number: 525a9779-4272-4ea5-9a11-4b9f7d876ed9"
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4167),
                            Message = "Error number: 39",
                            System = "System number: 9aa9355c-14ce-492e-b8a6-ab1654043798"
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4194),
                            Message = "Error number: 40",
                            System = "System number: 5c895b70-8326-4fd5-bdee-ed50497bf488"
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4200),
                            Message = "Error number: 41",
                            System = "System number: ed174d8e-95da-4924-93ed-e298be9d67cc"
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4204),
                            Message = "Error number: 42",
                            System = "System number: 0fb6b9bb-5aac-4d0a-a2c6-90b1dbd8fd23"
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4208),
                            Message = "Error number: 43",
                            System = "System number: 31a1df4b-99b1-4b65-9101-33bcaa6d527c"
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4212),
                            Message = "Error number: 44",
                            System = "System number: 9c819b8d-2b93-4c58-955a-1fc5cc98efb2"
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4216),
                            Message = "Error number: 45",
                            System = "System number: 46f2a402-ccad-4573-9381-0e514405c57b"
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4219),
                            Message = "Error number: 46",
                            System = "System number: d11f65ca-2911-41ee-87c3-241993ca2a6d"
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4223),
                            Message = "Error number: 47",
                            System = "System number: 7e237df5-1b1f-45ac-a218-34094143aa43"
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4227),
                            Message = "Error number: 48",
                            System = "System number: 1417dc5c-e4e8-40aa-af4e-74324c67ce35"
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4232),
                            Message = "Error number: 49",
                            System = "System number: b2f750ae-fab9-4efb-ae12-d07da24ce840"
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4236),
                            Message = "Error number: 50",
                            System = "System number: 62e033d8-ee01-49ef-8d22-c1db19c73c76"
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4240),
                            Message = "Error number: 51",
                            System = "System number: 62ed296b-725a-4a09-a355-56fa49d306ad"
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4244),
                            Message = "Error number: 52",
                            System = "System number: 073533c9-7001-49c9-9c85-3c114e56987a"
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4248),
                            Message = "Error number: 53",
                            System = "System number: 1d5f867b-02a9-4cd9-a304-6f29d457535d"
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4251),
                            Message = "Error number: 54",
                            System = "System number: 090fb4e9-9633-47d2-92ed-2ec80ad0d767"
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4255),
                            Message = "Error number: 55",
                            System = "System number: e0e37f3f-8e4c-4381-a96b-26d07d4fc63a"
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4259),
                            Message = "Error number: 56",
                            System = "System number: d695c2af-75ea-48d6-ad6e-908cb25b30bd"
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4264),
                            Message = "Error number: 57",
                            System = "System number: 582d194c-1290-4fd7-8a7a-cecb670b5bd8"
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4268),
                            Message = "Error number: 58",
                            System = "System number: 1ceadd69-cd4a-425c-9ca7-780d8dd1de9a"
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4272),
                            Message = "Error number: 59",
                            System = "System number: a13ffb50-410c-4cde-87af-28ffe40baa45"
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4276),
                            Message = "Error number: 60",
                            System = "System number: a67bcc02-c1cb-4279-be76-20c8e8119ce2"
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4279),
                            Message = "Error number: 61",
                            System = "System number: 1321c738-9524-461e-8b60-ee1cdab8600b"
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4283),
                            Message = "Error number: 62",
                            System = "System number: 14f9dec5-6ce0-493d-9848-c29a9802a87d"
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4313),
                            Message = "Error number: 63",
                            System = "System number: 560e937d-01ff-4445-9081-94737f22701b"
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4317),
                            Message = "Error number: 64",
                            System = "System number: 446fdb06-bb83-4966-88ad-0094ca940818"
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4322),
                            Message = "Error number: 65",
                            System = "System number: 4cfdf7b8-1fd0-4c14-b2b5-16d899ed769a"
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4327),
                            Message = "Error number: 66",
                            System = "System number: cb624e19-9dae-4463-96e5-d7f6b2185f20"
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4331),
                            Message = "Error number: 67",
                            System = "System number: f11bfa1d-6bf3-4fbf-a40c-7c808f168fa7"
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4335),
                            Message = "Error number: 68",
                            System = "System number: 7b073133-0b34-4611-8972-d213f4493fa8"
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2022, 7, 3, 21, 8, 41, 375, DateTimeKind.Local).AddTicks(4339),
                            Message = "Error number: 69",
                            System = "System number: cc3b2bef-b0e3-4ae5-9c0b-4b733d6b417a"
                        });
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Entity.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d953617e-7b84-4a52-890e-ed944a4354ac"),
                            IsActive = true,
                            Password = "AQAAAAEAACcQAAAAEI6Z8CxXD4b9OekjIav7zXZYemZJ7oZxEEA01xvYWFHaiR/4BhDJ9wk+VMNTh+w3Kg==",
                            RefreshToken = "",
                            RoleId = 2,
                            Username = "AdminUser"
                        },
                        new
                        {
                            Id = new Guid("7758d964-e2ec-44e2-8bdd-3607a019d1ee"),
                            IsActive = true,
                            Password = "AQAAAAEAACcQAAAAEHe65MJzIMW/oSj6Tk/LGKGDp8KZMJfgozsfIQhooO72X9HaaE7MxpZdDRdn6HrJwg==",
                            RefreshToken = "",
                            RoleId = 1,
                            Username = "BasicUser"
                        });
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Entity.UserEntity", b =>
                {
                    b.HasOne("Dashboard.Infrastructure.Entity.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
