// <auto-generated />
using System;
using Dashboard.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210403103024_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Dashboard.Server.Context.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a8e303f-e53c-43db-a934-2bfc9509e639"),
                            Password = "AQAAAAEAACcQAAAAEAskc5U/1Go51MDCofosdsbF8a3AQCCgE9y5us7kj4TImEvjE4pHIlYabzI8sycY1A==",
                            Username = "Dashboard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
